version: '3.9'

services:  
  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      environment:
          - PGADMIN_DEFAULT_EMAIL=kiehast@gmail.com
          - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
          - "5050:80"
  
networks:
  default:
    name: solace-net



