version: '3.9'

services:  
  server:
      container_name: solace-subscriber
      build:
          context: .
          dockerfile: Dockerfile
      image: solace-subscriber:latest
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://database-2.c1os8mensd7x.ap-southeast-2.rds.amazonaws.com:5432/solace     
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=Thursday5$
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
        - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

      ports:
        - 8080:8080
  
networks:
  default:
    name: solace-net



